/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NavBar: typeof import('./../src/components/navBar/index.vue')['default']
    Page404: typeof import('./../src/components/Page404.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSetting: typeof import('./../src/components/dialog/theme-setting.vue')['default']
  }
}
